# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Time Base' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "RxSwift"
  pod "RxCocoa"
  # Pods for Time Base

end
