# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Day8_Transforming' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day8_Transforming
    pod 'RxSwift', '6.2.0'
    pod 'RxCocoa', '6.2.0'
  target 'Day8_TransformingTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxBlocking', '6.2.0'
    	pod 'RxTest', '6.2.0'
  end

  target 'Day8_TransformingUITests' do
    # Pods for testing
  end

end
