# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Day10_TimeBased_Operators' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Day10_TimeBased_Operators
  	pod 'RxSwift', '6.2.0'
    	pod 'RxCocoa', '6.2.0'
  target 'Day10_TimeBased_OperatorsTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'RxBlocking', '6.2.0'
    	pod 'RxTest', '6.2.0'
  end

  target 'Day10_TimeBased_OperatorsUITests' do
    # Pods for testing
	pod 'RxBlocking', '6.2.0'
    	pod 'RxTest', '6.2.0'
  end

end
